### ISSUE TITLE
Show balance of accounts in explorer.aeternity.io

### ISSUE THREAD

**Issue by Shelpin** [aeternity/mdw-frontend#72] opened 2021-05-12 13:42 UTC
Currently when you access the detail of an account, there is no info on the balance of that account, could you please have a look to this @mradkov ?

![image](https://user-images.githubusercontent.com/21328788/117984757-65a84880-b338-11eb-8829-0ae667dd3dcf.png)

**Comment by marc0olo** [comment] 2021-08-24 11:29
duplicate of #28

**Closed by marc0olo** 2021-08-24 11:29 UTC
Labels: triage/duplicate, kind/enhancement, area/accounts
